# Generated by Django 4.2.6 on 2023-10-18 17:18

'''This is the step between the relationship between python and SQL'''

'''In order to setup our database, we need to make a model, then run 
python manage.py makemigrations 
python manage.py migrate'''

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
